version: '3.8'
services: 
  web:
      container_name: fresh-farm-app
      build: .
      ports:
        - "4200:80"
      depends_on:
        - db
        - cache

  db:
      image: postgres-alpine  
      container_name:
      restart: always
      build:
      ports:
        -  5432:5432
      environment:
        postgres_password: 71c394clint

  cache:
      image: 
      ports:
        -      